#!/usr/bin/env bash
# installs nginx onto a web server
sudo apt-get update
sudo apt-get -y install nginx
echo 'Hello World!' > /var/www/html/index.html
sed -i "/server_name _;/ a\\\trewrite ^/redirect_me https://ansi.org permanent;" /etc/nginx/sites-available/default
echo "Ceci n'est pas une page" > /var/www/html/c_404.html
sed -i "/redirect_me/ a\\\terror_page 404 /c_404.html;" /etc/nginx/sites-available/default
service nginx start
