#!/usr/bin/env bash
# installs nginx onto a web server
# sudo apt-get update
# sudo apt-get -y install nginx
# echo 'Hello World!' > /var/www/html/index.html

# chown -R "$USER":"$USER" /var/www/html
# chmod -R 755 /var/www

# Redirect to /redirect_me to a youtube video
# sed -i '37i\rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default

# 404 page
echo "Ceci n'est pas une page" >> /var/www/html/error_404.html
echo "" >> /var/www/html/error_404.html
sudo sed -i '38i\error_page 404 /error_404.html;' /etc/nginx/sites-available/default

# service nginx start
