#!/usr/bin/env bash
# configure Nginx to add a custom http header
# shellcheck disable=SC2154
sudo chown ubuntu:ubuntu /etc/nginx/sites-available/default
sudo ufw allow 'Nginx HTTP'
sudo sed -i "/listen 80 default_server/a \\\trewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;" /etc/nginx/sites-available/default
sudo sed -i "/listen 80 default_server/a \\\terror_page 404 /custom_404.html; location = /error_404.html {root /usr/share/nginx/html;\n\tinternal;}" /etc/nginx/sites-available/default
sudo sed -i "/listen 80 default_server/a \\\tadd_header X-Served-By $(hostname);" /etc/nginx/sites-available/default

sudo service nginx restart
