#!/usr/bin/env bash
# configure Nginx to add a custom http header
# shellcheck disable=SC2154
sudo chown ubuntu:ubuntu /etc/nginx/sites-available/default
sed -i "59i\\t\tadd_header X-Served-By $(hostname);" /etc/nginx/sites-available/default
