#!/usr/bin/env bash
# Installs the load balancer on ubuntu server lb-01
sudo apt-get update
sudo apt-get install --no-install-recommends software-properties-common
sudo add-apt-repository ppa:vbernat/haproxy-1.6
sudo apt-get install haproxy=1.6.\*
echo "ENABLED=1" >> /etc/default/haproxy
sudo sed -i "/504.http/a \\nlisten http-in\n\tbind *:80\n\tmode http\n\tbalance roundrobin\n\tserver 1231-web-01 34.74.70.205:80 check\n\tserver 1231-web-02 34.224.30.177:80 check" /etc/haproxy/haproxy.cfg
sudo service haproxy start
