#!/usr/bin/env bash
# let's try print the clock till midnight

HOUR=1
echo echo "Hour: 0"
while [ $HOUR -le 13 ]; do
    minute=1
    while [ $minute -lt 60 ]; do
	echo "$minute"
	(( minute++ ))
    done

    if (( HOUR <= 12 ))
    then
	echo "Hour: $HOUR"
    fi
    (( HOUR++ ))
done
