#!/usr/bin/env bash
# Change Home Address and assign 8.8.8.8 to facebook.com

sudo cp /etc/hosts ~/hosts.new
sudo cp /etc/hosts ~/hosts.old
sed -i s/127.0.0.1/127.0.0.2/ ~/hosts.new
echo "8.8.8.8		      facebook.com" >> ~/hosts.new
sudo cp ~/hosts.new /etc/hosts
