#!/usr/bin/env bash
# changes nginx configuration to run as nginx user
# sudo chown nginx:nginx /etc/nginx/nginx.conf
pkill -f apache2
sudo chmod 644 /etc/nginx/nginx.conf
sed -i '1i user nginx;' /etc/nginx/nginx.conf
# sudo service nginx restart
sudo sed -i 's/80/8080/' /etc/nginx/sites-enabled/default
sudo -u nginx service nginx restart
