#!/usr/bin/env bash
# changes nginx configuration to run as nginx user
# sudo chown nginx:nginx /etc/nginx/nginx.conf
sudo sed -i '1 /s/#user www-data;.*/user nginx;' /etc/nginx/nginx.conf
sudo service nginx restart
sudo sed -i 's/listen 80 default_server;.*/listen 8080 default_server;/' /etc/nginx/sites-enabled/default
sudo sed -i 's/listen \[::\]:80 default_server ipv6only=on;.*/listen \[::\]:8080 default_server;/' /etc/nginx/sites-enabled/default
sudo service nginx restart
