#!/usr/bin/env bash
# changes nginx configuration to run as nginx user
sudo chmod 644 /etc/nginx/nginx.conf
sed -i '1i user nginx;' /etc/nginx/nginx.conf
sudo sed -i 's/80/8080/' /etc/nginx/sites-enabled/default
sudo -u nginx service nginx restart
